//go:build bls12381

// Package compat holds the bera-v1.x <-> bera-v0.40.x compatibility tests.
//
// vectors_test.go replays a fixed set of inputs through this fork and asserts
// that every consensus-relevant byte string (sign bytes, signatures, hashes,
// persisted protos, p2p/WAL wire messages, key and genesis files) is identical
// to what the bera-v1.x line produces for the same inputs. The expected values
// live in vectors/bera_v1x_vectors.json and are generated by gen-v1x/ (which
// builds against bera-v1.x); the inputs below must stay in sync with gen-v1x.
package compat

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	gogo "github.com/cosmos/gogoproto/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	abci "github.com/cometbft/cometbft/abci/types"
	"github.com/cometbft/cometbft/crypto"
	"github.com/cometbft/cometbft/crypto/bls12381"
	"github.com/cometbft/cometbft/crypto/ed25519"
	"github.com/cometbft/cometbft/libs/bits"
	cmtjson "github.com/cometbft/cometbft/libs/json"
	"github.com/cometbft/cometbft/privval"
	cmtcons "github.com/cometbft/cometbft/proto/tendermint/consensus"
	cmtstate "github.com/cometbft/cometbft/proto/tendermint/state"
	cmtstore "github.com/cometbft/cometbft/proto/tendermint/store"
	cmtproto "github.com/cometbft/cometbft/proto/tendermint/types"
	cmtversion "github.com/cometbft/cometbft/proto/tendermint/version"
	sm "github.com/cometbft/cometbft/state"
	"github.com/cometbft/cometbft/types"
)

// Fixed inputs. Keep in sync with gen-v1x/main.go.
const (
	chainID  = "bera-compat-1"
	height   = int64(1234)
	round    = int32(2)
	numVals  = 4
	blsSeed  = "bera-compat-bls-val-"
	ed25Seed = "bera-compat-ed25519-val"
)

var (
	fixedTime     = time.Date(2026, 1, 2, 3, 4, 5, 600000000, time.UTC)
	fixedTimeNext = fixedTime.Add(2 * time.Second)
	powers        = []int64{10, 20, 30, 40}
)

func h32(label string) []byte { s := sha256.Sum256([]byte(label)); return s[:] }

type vectors map[string]any

func loadVectors(t *testing.T) vectors {
	t.Helper()
	bz, err := os.ReadFile(filepath.Join("vectors", "bera_v1x_vectors.json"))
	require.NoError(t, err)
	v := vectors{}
	require.NoError(t, json.Unmarshal(bz, &v))
	return v
}

func (v vectors) hex(t *testing.T, key string) []byte {
	t.Helper()
	s, ok := v[key].(string)
	require.Truef(t, ok, "vector %q missing or not a string", key)
	bz, err := hex.DecodeString(s)
	require.NoErrorf(t, err, "vector %q is not hex", key)
	return bz
}

func (v vectors) str(t *testing.T, key string) string {
	t.Helper()
	s, ok := v[key].(string)
	require.Truef(t, ok, "vector %q missing or not a string", key)
	return s
}

func (v vectors) num(t *testing.T, key string) int {
	t.Helper()
	f, ok := v[key].(float64)
	require.Truef(t, ok, "vector %q missing or not a number", key)
	return int(f)
}

// eqHex asserts that got equals the hex vector named key.
func (v vectors) eqHex(t *testing.T, key string, got []byte) {
	t.Helper()
	want := v.hex(t, key)
	assert.Equalf(t, hex.EncodeToString(want), hex.EncodeToString(got), "vector %q differs from bera-v1.x", key)
}

type marshaler interface{ Marshal() ([]byte, error) }

func mustMarshal(t *testing.T, m marshaler) []byte {
	t.Helper()
	bz, err := m.Marshal()
	require.NoError(t, err)
	return bz
}

func blsPubPtr(pk crypto.PubKey) *bls12381.PubKey {
	switch k := pk.(type) {
	case *bls12381.PubKey:
		return k
	case bls12381.PubKey:
		return &k
	default:
		panic(fmt.Sprintf("not a BLS public key: %T", pk))
	}
}

func sortKeys[K any](valSet *types.ValidatorSet, vals []*types.Validator, privs []K) ([]*types.Validator, []K) {
	outVals := make([]*types.Validator, len(vals))
	outPrivs := make([]K, len(privs))
	for i, sv := range valSet.Validators {
		found := false
		for j, v := range vals {
			if bytes.Equal(v.PubKey.Bytes(), sv.PubKey.Bytes()) {
				outVals[i] = sv
				outPrivs[i] = privs[j]
				found = true
				break
			}
		}
		if !found {
			panic("validator not found")
		}
	}
	return outVals, outPrivs
}

// fixture holds everything derived from the fixed inputs.
type fixture struct {
	blsPrivs  []*bls12381.PrivKey
	blsVals   []*types.Validator
	blsValSet *types.ValidatorSet
	edPriv    ed25519.PrivKey
	edPrivs   []ed25519.PrivKey
	edVals    []*types.Validator
	edValSet  *types.ValidatorSet
	blockID   types.BlockID
	params    types.ConsensusParams
}

func newFixture(t *testing.T) *fixture {
	t.Helper()
	f := &fixture{}
	f.blsPrivs = make([]*bls12381.PrivKey, numVals)
	f.blsVals = make([]*types.Validator, numVals)
	for i := 0; i < numVals; i++ {
		pk, err := bls12381.GenPrivKeyFromSecret([]byte(fmt.Sprintf("%s%d", blsSeed, i)))
		require.NoError(t, err)
		f.blsPrivs[i] = pk
		f.blsVals[i] = types.NewValidator(pk.PubKey(), powers[i])
	}
	f.blsValSet = types.NewValidatorSet(f.blsVals)
	f.blsVals, f.blsPrivs = sortKeys(f.blsValSet, f.blsVals, f.blsPrivs)

	f.edPriv = ed25519.GenPrivKeyFromSecret([]byte(ed25Seed))
	f.edPrivs = make([]ed25519.PrivKey, numVals)
	f.edVals = make([]*types.Validator, numVals)
	for i := 0; i < numVals; i++ {
		f.edPrivs[i] = ed25519.GenPrivKeyFromSecret([]byte(fmt.Sprintf("%s-%d", ed25Seed, i)))
		f.edVals[i] = types.NewValidator(f.edPrivs[i].PubKey(), powers[i])
	}
	f.edValSet = types.NewValidatorSet(f.edVals)
	f.edVals, f.edPrivs = sortKeys(f.edValSet, f.edVals, f.edPrivs)

	f.blockID = types.BlockID{
		Hash:          h32("block"),
		PartSetHeader: types.PartSetHeader{Total: 3, Hash: h32("parts")},
	}
	f.params = types.ConsensusParams{
		Block:     types.BlockParams{MaxBytes: 104857600, MaxGas: -1},
		Evidence:  types.EvidenceParams{MaxAgeNumBlocks: 100000, MaxAgeDuration: 172800 * time.Second, MaxBytes: 1048576},
		Validator: types.ValidatorParams{PubKeyTypes: []string{types.ABCIPubKeyTypeBls12381}},
		Version:   types.VersionParams{App: 1},
		Synchrony: types.SynchronyParams{Precision: 505 * time.Millisecond, MessageDelay: 15 * time.Second},
		Feature:   types.FeatureParams{VoteExtensionsEnableHeight: 0, PbtsEnableHeight: 1, SBTEnableHeight: 7},
	}
	return f
}

func (f *fixture) vote(tp cmtproto.SignedMsgType, bid types.BlockID, valIdx int32, addr []byte) *types.Vote {
	return &types.Vote{
		Type:             tp,
		Height:           height,
		Round:            round,
		BlockID:          bid,
		ValidatorAddress: addr,
		ValidatorIndex:   valIdx,
		Timestamp:        time.Time{},
	}
}

func (f *fixture) signedBLSVote(t *testing.T, bid types.BlockID, i int) *types.Vote {
	t.Helper()
	vote := f.vote(cmtproto.PrecommitType, bid, int32(i), f.blsVals[i].Address)
	sig, err := f.blsPrivs[i].Sign(types.VoteSignBytes(chainID, vote.ToProto()))
	require.NoError(t, err)
	vote.Signature = sig
	return vote
}

// aggCommit builds the aggregated commit where validators 0..2 commit and 3 votes nil.
func (f *fixture) aggCommit(t *testing.T) *types.Commit {
	t.Helper()
	voteSet := types.NewVoteSet(chainID, height, round, cmtproto.PrecommitType, f.blsValSet)
	for i := 0; i < numVals; i++ {
		bid := f.blockID
		if i == 3 {
			bid = types.BlockID{}
		}
		added, err := voteSet.AddVote(f.signedBLSVote(t, bid, i))
		require.NoError(t, err)
		require.True(t, added)
	}
	return voteSet.MakeBLSCommit().ToCommit()
}

func TestVectorsKeysAndValidators(t *testing.T) {
	v := loadVectors(t)
	f := newFixture(t)

	// keyed by seed index (creation order), independent of validator-set order
	for i := 0; i < numVals; i++ {
		pk, err := bls12381.GenPrivKeyFromSecret([]byte(fmt.Sprintf("%s%d", blsSeed, i)))
		require.NoError(t, err)
		v.eqHex(t, fmt.Sprintf("bls_pubkey_%d", i), pk.PubKey().Bytes())
		v.eqHex(t, fmt.Sprintf("bls_pubkey_compressed_%d", i), blsPubPtr(pk.PubKey()).Compress())
		v.eqHex(t, fmt.Sprintf("bls_address_%d", i), pk.PubKey().Address())
	}
	v.eqHex(t, "bls_valset_hash", f.blsValSet.Hash())
	vsp, err := f.blsValSet.ToProto()
	require.NoError(t, err)
	v.eqHex(t, "bls_valset_proto", mustMarshal(t, vsp))
	vp, err := f.blsVals[0].ToProto()
	require.NoError(t, err)
	v.eqHex(t, "bls_validator0_proto", mustMarshal(t, vp))
	v.eqHex(t, "bls_validator0_bytes", f.blsVals[0].Bytes())

	// a validator set decoded from the bera-v1.x proto hashes identically
	decoded := new(cmtproto.ValidatorSet)
	require.NoError(t, decoded.Unmarshal(v.hex(t, "bls_valset_proto")))
	vs2, err := types.ValidatorSetFromProto(decoded)
	require.NoError(t, err)
	v.eqHex(t, "bls_valset_hash", vs2.Hash())

	v.eqHex(t, "ed25519_pubkey", f.edPriv.PubKey().Bytes())
	v.eqHex(t, "ed25519_address", f.edPriv.PubKey().Address())
	edVal := types.NewValidator(f.edPriv.PubKey(), 5)
	vp, err = edVal.ToProto()
	require.NoError(t, err)
	v.eqHex(t, "ed25519_validator_proto", mustMarshal(t, vp))
	v.eqHex(t, "ed25519_valset_hash", f.edValSet.Hash())
}

func TestVectorsSignBytes(t *testing.T) {
	v := loadVectors(t)
	f := newFixture(t)

	bidp := f.blockID.ToProto()
	v.eqHex(t, "blockid_proto", mustMarshal(t, &bidp))

	precommit := f.vote(cmtproto.PrecommitType, f.blockID, 0, f.blsVals[0].Address)
	prevote := f.vote(cmtproto.PrevoteType, f.blockID, 0, f.blsVals[0].Address)
	nilPrecommit := f.vote(cmtproto.PrecommitType, types.BlockID{}, 3, f.blsVals[3].Address)
	v.eqHex(t, "vote_sign_bytes_precommit", types.VoteSignBytes(chainID, precommit.ToProto()))
	v.eqHex(t, "vote_sign_bytes_prevote", types.VoteSignBytes(chainID, prevote.ToProto()))
	v.eqHex(t, "vote_sign_bytes_nil_precommit", types.VoteSignBytes(chainID, nilPrecommit.ToProto()))
	sig, err := f.blsPrivs[0].Sign(types.VoteSignBytes(chainID, precommit.ToProto()))
	require.NoError(t, err)
	v.eqHex(t, "vote_bls_signature_val0_precommit", sig)
	precommit.Signature = sig
	v.eqHex(t, "vote_proto_signed_precommit", mustMarshal(t, precommit.ToProto()))
	require.NoError(t, precommit.ValidateBasic())
	require.NoError(t, precommit.Verify(chainID, f.blsVals[0].PubKey))

	tsVote := f.vote(cmtproto.PrecommitType, f.blockID, 0, f.blsVals[0].Address)
	tsVote.Timestamp = fixedTime
	v.eqHex(t, "vote_sign_bytes_precommit_with_timestamp", types.VoteSignBytes(chainID, tsVote.ToProto()))

	proposal := types.NewProposal(height, round, 1, f.blockID, fixedTime)
	v.eqHex(t, "proposal_sign_bytes", types.ProposalSignBytes(chainID, proposal.ToProto()))
	psig, err := f.blsPrivs[1].Sign(types.ProposalSignBytes(chainID, proposal.ToProto()))
	require.NoError(t, err)
	v.eqHex(t, "proposal_bls_signature_val1", psig)
	proposal.Signature = psig
	v.eqHex(t, "proposal_proto_signed", mustMarshal(t, proposal.ToProto()))
	require.NoError(t, proposal.ValidateBasic())

	// a bera-v1.x signed vote decodes and verifies here
	pv := new(cmtproto.Vote)
	require.NoError(t, pv.Unmarshal(v.hex(t, "vote_proto_signed_precommit")))
	vote, err := types.VoteFromProto(pv)
	require.NoError(t, err)
	require.NoError(t, vote.ValidateBasic())
	require.NoError(t, vote.Verify(chainID, f.blsVals[0].PubKey))
}

func TestVectorsCommits(t *testing.T) {
	v := loadVectors(t)
	f := newFixture(t)

	agg := f.aggCommit(t)
	v.eqHex(t, "agg_commit_proto", mustMarshal(t, agg.ToProto()))
	v.eqHex(t, "agg_commit_hash", agg.Hash())
	for i, cs := range agg.Signatures {
		assert.Equal(t, v.num(t, fmt.Sprintf("agg_commit_sig%d_flag", i)), int(cs.BlockIDFlag), "sig %d flag", i)
	}
	require.True(t, agg.HasAggregatedSignature())
	require.NoError(t, f.blsValSet.VerifyCommit(chainID, f.blockID, height, agg))
	require.NoError(t, types.VerifyCommitLight(chainID, f.blsValSet, f.blockID, height, agg))

	// a bera-v1.x aggregated commit decodes, hashes and verifies here
	pc := new(cmtproto.Commit)
	require.NoError(t, pc.Unmarshal(v.hex(t, "agg_commit_proto")))
	c2, err := types.CommitFromProto(pc)
	require.NoError(t, err)
	require.NoError(t, c2.ValidateBasic())
	v.eqHex(t, "agg_commit_hash", c2.Hash())
	require.NoError(t, f.blsValSet.VerifyCommit(chainID, f.blockID, height, c2))

	voteSet2 := types.NewVoteSet(chainID, height, round, cmtproto.PrecommitType, f.blsValSet)
	for i := 0; i < numVals; i++ {
		_, err := voteSet2.AddVote(f.signedBLSVote(t, f.blockID, i))
		require.NoError(t, err)
	}
	aggAll := voteSet2.MakeBLSCommit().ToCommit()
	v.eqHex(t, "agg_commit_all_proto", mustMarshal(t, aggAll.ToProto()))
	v.eqHex(t, "agg_commit_all_hash", aggAll.Hash())
	require.NoError(t, f.blsValSet.VerifyCommit(chainID, f.blockID, height, aggAll))

	edVoteSet := types.NewVoteSet(chainID, height, round, cmtproto.PrecommitType, f.edValSet)
	for i := 0; i < numVals; i++ {
		bid := f.blockID
		if i == 1 {
			bid = types.BlockID{}
		}
		vote := f.vote(cmtproto.PrecommitType, bid, int32(i), f.edVals[i].Address)
		sig, err := f.edPrivs[i].Sign(types.VoteSignBytes(chainID, vote.ToProto()))
		require.NoError(t, err)
		vote.Signature = sig
		_, err = edVoteSet.AddVote(vote)
		require.NoError(t, err)
	}
	edCommit := edVoteSet.MakeExtendedCommit(types.FeatureParams{}).ToCommit()
	v.eqHex(t, "ed25519_commit_proto", mustMarshal(t, edCommit.ToProto()))
	v.eqHex(t, "ed25519_commit_hash", edCommit.Hash())
	require.NoError(t, f.edValSet.VerifyCommit(chainID, f.blockID, height, edCommit))
}

func durPtr(d time.Duration) *time.Duration { return &d }

func paramsUpdate() *cmtproto.ConsensusParams {
	return &cmtproto.ConsensusParams{
		Block:     &cmtproto.BlockParams{MaxBytes: 1, MaxGas: 2},
		Feature:   &cmtproto.FeatureParams{SbtEnableHeight: &gogo.Int64Value{Value: 9}},
		Synchrony: &cmtproto.SynchronyParams{Precision: durPtr(1 * time.Second), MessageDelay: durPtr(3 * time.Second)},
	}
}

func TestVectorsConsensusParams(t *testing.T) {
	v := loadVectors(t)
	f := newFixture(t)

	v.eqHex(t, "params_hash", f.params.Hash())
	pp := f.params.ToProto()
	v.eqHex(t, "params_proto", mustMarshal(t, &pp))
	bz, err := cmtjson.Marshal(f.params)
	require.NoError(t, err)
	// The JSON form is what genesis files carry. This fork adds an "authority"
	// object (upstream v0.39+), so compare the bera-v1.x keys as a subset and
	// require the extra object to be empty.
	var got, want map[string]json.RawMessage
	require.NoError(t, json.Unmarshal(bz, &got))
	require.NoError(t, json.Unmarshal([]byte(v.str(t, "params_json")), &want))
	for k, wv := range want {
		assert.JSONEqf(t, string(wv), string(got[k]), "consensus_params.%s JSON differs", k)
		delete(got, k)
	}
	for k, gv := range got {
		assert.Equalf(t, "authority", k, "unexpected extra consensus_params key %q", k)
		assert.JSONEq(t, `{"authority":""}`, string(gv))
	}

	// params decoded from the bera-v1.x proto are identical
	pbp := new(cmtproto.ConsensusParams)
	require.NoError(t, pbp.Unmarshal(v.hex(t, "params_proto")))
	decoded := types.ConsensusParamsFromProto(*pbp)
	assert.Equal(t, f.params, decoded)
	v.eqHex(t, "params_hash", decoded.Hash())
	require.NoError(t, decoded.ValidateBasic())

	upd := paramsUpdate()
	v.eqHex(t, "params_update_proto", mustMarshal(t, upd))
	updated := f.params.Update(upd)
	v.eqHex(t, "params_updated_hash", updated.Hash())
	up := updated.ToProto()
	v.eqHex(t, "params_updated_proto", mustMarshal(t, &up))
	assert.EqualValues(t, 9, updated.Feature.SBTEnableHeight)
	assert.Equal(t, 3*time.Second, updated.Synchrony.MessageDelay)
	assert.EqualValues(t, 1, updated.Feature.PbtsEnableHeight)
}

func (f *fixture) block(t *testing.T, agg *types.Commit) (*types.Block, *types.PartSet) {
	t.Helper()
	lastBlockID := types.BlockID{Hash: h32("last-block"), PartSetHeader: types.PartSetHeader{Total: 1, Hash: h32("last-parts")}}
	txs := []types.Tx{types.Tx("tx-one"), types.Tx("tx-two")}
	block := types.MakeBlock(height+1, txs, agg, nil)
	block.Header.Version = cmtversion.Consensus{Block: 11, App: 1}
	block.Header.ChainID = chainID
	block.Header.Time = fixedTimeNext
	block.Header.LastBlockID = lastBlockID
	block.Header.ValidatorsHash = f.blsValSet.Hash()
	block.Header.NextValidatorsHash = f.blsValSet.Hash()
	block.Header.ConsensusHash = f.params.Hash()
	block.Header.AppHash = h32("app")
	block.Header.LastResultsHash = h32("results")
	block.Header.ProposerAddress = f.blsVals[1].Address
	block.Header.EvidenceHash = block.Evidence.Hash()
	block.Header.DataHash = block.Data.Hash()
	block.Header.LastCommitHash = agg.Hash()
	ps, err := block.MakePartSet(types.BlockPartSizeBytes)
	require.NoError(t, err)
	return block, ps
}

func TestVectorsBlock(t *testing.T) {
	v := loadVectors(t)
	f := newFixture(t)
	agg := f.aggCommit(t)
	block, ps := f.block(t, agg)

	v.eqHex(t, "header_hash", block.Header.Hash())
	hp := block.Header.ToProto()
	v.eqHex(t, "header_proto", mustMarshal(t, hp))
	v.eqHex(t, "block_hash", block.Hash())
	bp, err := block.ToProto()
	require.NoError(t, err)
	v.eqHex(t, "block_proto", mustMarshal(t, bp))
	assert.Equal(t, v.num(t, "block_partset_total"), int(ps.Total()))
	v.eqHex(t, "block_partset_hash", ps.Hash())
	partp, err := ps.GetPart(0).ToProto()
	require.NoError(t, err)
	v.eqHex(t, "block_part0_proto", mustMarshal(t, partp))
	v.eqHex(t, "data_hash", block.Data.Hash())
	v.eqHex(t, "evidence_hash_empty", block.Evidence.Hash())
	meta := types.NewBlockMeta(block, ps)
	v.eqHex(t, "block_meta_proto", mustMarshal(t, meta.ToProto()))

	// a bera-v1.x block decodes, validates and hashes identically
	pbb := new(cmtproto.Block)
	require.NoError(t, pbb.Unmarshal(v.hex(t, "block_proto")))
	b2, err := types.BlockFromProto(pbb)
	require.NoError(t, err)
	require.NoError(t, b2.ValidateBasic())
	v.eqHex(t, "block_hash", b2.Hash())
	v.eqHex(t, "agg_commit_hash", b2.LastCommit.Hash())
	require.NoError(t, f.blsValSet.VerifyCommit(chainID, f.blockID, height, b2.LastCommit))
	pbm := new(cmtproto.BlockMeta)
	require.NoError(t, pbm.Unmarshal(v.hex(t, "block_meta_proto")))
	m2, err := types.BlockMetaFromProto(pbm)
	require.NoError(t, err)
	v.eqHex(t, "block_hash", m2.BlockID.Hash)
	v.eqHex(t, "block_partset_hash", m2.BlockID.PartSetHeader.Hash)
}

func TestVectorsEvidence(t *testing.T) {
	v := loadVectors(t)
	f := newFixture(t)

	voteA := f.signedBLSVote(t, f.blockID, 2)
	otherBlockID := types.BlockID{Hash: h32("other-block"), PartSetHeader: types.PartSetHeader{Total: 3, Hash: h32("other-parts")}}
	voteB := f.signedBLSVote(t, otherBlockID, 2)
	dve, err := types.NewDuplicateVoteEvidence(voteA, voteB, fixedTime, f.blsValSet)
	require.NoError(t, err)
	require.NoError(t, dve.ValidateBasic())
	v.eqHex(t, "dve_hash", dve.Hash())
	evp, err := types.EvidenceToProto(dve)
	require.NoError(t, err)
	v.eqHex(t, "dve_proto", mustMarshal(t, evp))
	v.eqHex(t, "dve_bytes", dve.Bytes())
	v.eqHex(t, "evidence_list_hash", types.EvidenceList{dve}.Hash())

	// bera-v1.x evidence decodes and hashes identically
	pe := new(cmtproto.Evidence)
	require.NoError(t, pe.Unmarshal(v.hex(t, "dve_proto")))
	ev, err := types.EvidenceFromProto(pe)
	require.NoError(t, err)
	require.NoError(t, ev.ValidateBasic())
	v.eqHex(t, "dve_hash", ev.Hash())
}

func TestVectorsPersistedState(t *testing.T) {
	v := loadVectors(t)
	f := newFixture(t)

	state := sm.State{
		Version: cmtstate.Version{
			Consensus: cmtversion.Consensus{Block: 11, App: 1},
			Software:  "1.0.1",
		},
		ChainID:                          chainID,
		InitialHeight:                    1,
		LastBlockHeight:                  height,
		LastBlockID:                      f.blockID,
		LastBlockTime:                    fixedTime,
		NextValidators:                   f.blsValSet.Copy(),
		Validators:                       f.blsValSet.Copy(),
		LastValidators:                   f.blsValSet.Copy(),
		LastHeightValidatorsChanged:      100,
		ConsensusParams:                  f.params,
		LastHeightConsensusParamsChanged: 50,
		LastResultsHash:                  h32("results"),
		AppHash:                          h32("app"),
		NextBlockDelay:                   1500 * time.Millisecond,
	}
	sp, err := state.ToProto()
	require.NoError(t, err)
	v.eqHex(t, "state_proto", mustMarshal(t, sp))

	// the bera-v1.x persisted state loads into an identical State and
	// round-trips byte-for-byte
	psm := new(cmtstate.State)
	require.NoError(t, psm.Unmarshal(v.hex(t, "state_proto")))
	loaded, err := sm.FromProto(psm)
	require.NoError(t, err)
	assert.Equal(t, state.ChainID, loaded.ChainID)
	assert.Equal(t, state.LastBlockHeight, loaded.LastBlockHeight)
	assert.Equal(t, state.LastBlockID, loaded.LastBlockID)
	assert.True(t, state.LastBlockTime.Equal(loaded.LastBlockTime))
	assert.Equal(t, state.NextBlockDelay, loaded.NextBlockDelay)
	assert.Equal(t, state.ConsensusParams, loaded.ConsensusParams)
	assert.Equal(t, state.Validators.Hash(), loaded.Validators.Hash())
	assert.Equal(t, state.LastResultsHash, loaded.LastResultsHash)
	assert.Equal(t, state.AppHash, loaded.AppHash)
	rt, err := loaded.ToProto()
	require.NoError(t, err)
	v.eqHex(t, "state_proto", mustMarshal(t, rt))

	vsp, err := f.blsValSet.ToProto()
	require.NoError(t, err)
	valInfo := &cmtstate.ValidatorsInfo{ValidatorSet: vsp, LastHeightChanged: 100}
	v.eqHex(t, "validators_info_proto", mustMarshal(t, valInfo))
	ppp := f.params.ToProto()
	cpInfo := &cmtstate.ConsensusParamsInfo{ConsensusParams: ppp, LastHeightChanged: 50}
	v.eqHex(t, "consensus_params_info_proto", mustMarshal(t, cpInfo))

	bss := &cmtstore.BlockStoreState{Base: 1, Height: height}
	v.eqHex(t, "block_store_state_proto", mustMarshal(t, bss))
}

func TestVectorsABCIResponses(t *testing.T) {
	v := loadVectors(t)
	f := newFixture(t)

	// Build the response exactly as bera-v1.x persists it (validator updates
	// with pub_key_bytes + pub_key_type) and check the bytes match.
	fbr := &abci.ResponseFinalizeBlock{
		Events:    []abci.Event{{Type: "t", Attributes: []abci.EventAttribute{{Key: "k", Value: "v", Index: true}}}},
		TxResults: []*abci.ExecTxResult{{Code: 0, Data: []byte("d"), GasWanted: 1, GasUsed: 1}},
		ValidatorUpdates: []abci.ValidatorUpdate{{
			PubKeyBytes: blsPubPtr(f.blsPrivs[0].PubKey()).Compress(),
			PubKeyType:  bls12381.KeyType,
			Power:       77,
		}},
		ConsensusParamUpdates: paramsUpdate(),
		AppHash:               h32("app-next"),
		NextBlockDelay:        1500 * time.Millisecond,
	}
	// This fork's ValidatorUpdate.pub_key is a non-nullable message, so an
	// unset key is still written as an empty field 1 (bytes 0a 00); bera-v1.x
	// reserves field 1 and skips it. Everything else must be byte-identical,
	// so compare after removing that empty field from this fork's encoding.
	stripEmptyPubKey := func(bz []byte) []byte {
		return bytes.Replace(bz, []byte{0x1a, 0x41, 0x0a, 0x00, 0x10, 0x4d}, []byte{0x1a, 0x3f, 0x10, 0x4d}, 1)
	}
	v.eqHex(t, "finalize_block_response_proto", stripEmptyPubKey(mustMarshal(t, fbr)))
	respInfo := &cmtstate.ABCIResponsesInfo{ResponseFinalizeBlock: fbr, Height: height}
	v.eqHex(t, "abci_responses_info_proto", bytes.Replace(stripEmptyPubKey(mustMarshal(t, respInfo)), []byte{0x1a, 0x9f, 0x01}, []byte{0x1a, 0x9d, 0x01}, 1))

	// A bera-v1.x persisted response decodes fully: NextBlockDelay, params and
	// validator updates (including the public key) are recovered.
	got := new(cmtstate.ABCIResponsesInfo)
	require.NoError(t, got.Unmarshal(v.hex(t, "abci_responses_info_proto")))
	require.NotNil(t, got.ResponseFinalizeBlock)
	assert.Equal(t, height, got.Height)
	assert.Equal(t, 1500*time.Millisecond, got.ResponseFinalizeBlock.NextBlockDelay)
	assert.Equal(t, h32("app-next"), got.ResponseFinalizeBlock.AppHash)
	vals, err := types.PB2TM.ValidatorUpdates(got.ResponseFinalizeBlock.ValidatorUpdates)
	require.NoError(t, err)
	require.Len(t, vals, 1)
	assert.True(t, f.blsVals[0].PubKey.Equals(vals[0].PubKey))
	assert.EqualValues(t, 77, vals[0].VotingPower)
	updated := f.params.Update(got.ResponseFinalizeBlock.ConsensusParamUpdates)
	v.eqHex(t, "params_updated_hash", updated.Hash())

	ppr := &abci.RequestProcessProposal{
		Hash:                h32("block"),
		Height:              height,
		Time:                fixedTime,
		ProposerAddress:     f.blsVals[1].Address,
		NextValidatorsHash:  f.blsValSet.Hash(),
		NextProposerAddress: f.blsVals[2].Address,
	}
	v.eqHex(t, "process_proposal_request_proto", mustMarshal(t, ppr))
}

func (f *fixture) p2pMessages(t *testing.T) map[string]*cmtcons.Message {
	t.Helper()
	agg := f.aggCommit(t)
	_, ps := f.block(t, agg)
	partp, err := ps.GetPart(0).ToProto()
	require.NoError(t, err)
	precommit := f.signedBLSVote(t, f.blockID, 0)
	proposal := types.NewProposal(height, round, 1, f.blockID, fixedTime)
	psig, err := f.blsPrivs[1].Sign(types.ProposalSignBytes(chainID, proposal.ToProto()))
	require.NoError(t, err)
	proposal.Signature = psig
	ba := func(n, set int) *bits.BitArray {
		b := bits.NewBitArray(n)
		b.SetIndex(set, true)
		return b
	}
	return map[string]*cmtcons.Message{
		"p2p_new_round_step": {Sum: &cmtcons.Message_NewRoundStep{NewRoundStep: &cmtcons.NewRoundStep{
			Height: height, Round: round, Step: 3, SecondsSinceStartTime: 7, LastCommitRound: 1,
		}}},
		"p2p_new_valid_block": {Sum: &cmtcons.Message_NewValidBlock{NewValidBlock: &cmtcons.NewValidBlock{
			Height: height, Round: round, BlockPartSetHeader: f.blockID.PartSetHeader.ToProto(),
			BlockParts: ba(3, 1).ToProto(), IsCommit: true,
		}}},
		"p2p_proposal":     {Sum: &cmtcons.Message_Proposal{Proposal: &cmtcons.Proposal{Proposal: *proposal.ToProto()}}},
		"p2p_proposal_pol": {Sum: &cmtcons.Message_ProposalPol{ProposalPol: &cmtcons.ProposalPOL{Height: height, ProposalPolRound: 1, ProposalPol: *ba(4, 2).ToProto()}}},
		"p2p_block_part":   {Sum: &cmtcons.Message_BlockPart{BlockPart: &cmtcons.BlockPart{Height: height + 1, Round: round, Part: *partp}}},
		"p2p_vote":         {Sum: &cmtcons.Message_Vote{Vote: &cmtcons.Vote{Vote: precommit.ToProto()}}},
		"p2p_has_vote":     {Sum: &cmtcons.Message_HasVote{HasVote: &cmtcons.HasVote{Height: height, Round: round, Type: cmtproto.PrecommitType, Index: 2}}},
		"p2p_vote_set_maj23": {Sum: &cmtcons.Message_VoteSetMaj23{VoteSetMaj23: &cmtcons.VoteSetMaj23{
			Height: height, Round: round, Type: cmtproto.PrecommitType, BlockID: f.blockID.ToProto(),
		}}},
		"p2p_vote_set_bits": {Sum: &cmtcons.Message_VoteSetBits{VoteSetBits: &cmtcons.VoteSetBits{
			Height: height, Round: round, Type: cmtproto.PrecommitType, BlockID: f.blockID.ToProto(), Votes: *ba(4, 3).ToProto(),
		}}},
		"p2p_has_proposal_block_part": {Sum: &cmtcons.Message_HasProposalBlockPart{HasProposalBlockPart: &cmtcons.HasProposalBlockPart{
			Height: height + 1, Round: round, Index: 0,
		}}},
		"p2p_commit": {Sum: &cmtcons.Message_Commit{Commit: &cmtcons.Commit{Commit: agg.ToProto()}}},
	}
}

func TestVectorsConsensusP2PMessages(t *testing.T) {
	v := loadVectors(t)
	f := newFixture(t)
	msgs := f.p2pMessages(t)
	for name, m := range msgs {
		v.eqHex(t, name, mustMarshal(t, m))
		// and every bera-v1.x message decodes into the same message here
		decoded := new(cmtcons.Message)
		require.NoErrorf(t, decoded.Unmarshal(v.hex(t, name)), "decode %s", name)
		v.eqHex(t, name, mustMarshal(t, decoded))
	}
}

func TestVectorsWAL(t *testing.T) {
	v := loadVectors(t)
	f := newFixture(t)
	msgs := f.p2pMessages(t)

	walVote := &cmtcons.TimedWALMessage{
		Time: fixedTime,
		Msg:  &cmtcons.WALMessage{Sum: &cmtcons.WALMessage_MsgInfo{MsgInfo: &cmtcons.MsgInfo{Msg: *msgs["p2p_vote"], PeerID: ""}}},
	}
	v.eqHex(t, "wal_msginfo_vote_proto", mustMarshal(t, walVote))
	walTimeout := &cmtcons.TimedWALMessage{
		Time: fixedTime,
		Msg: &cmtcons.WALMessage{Sum: &cmtcons.WALMessage_TimeoutInfo{TimeoutInfo: &cmtcons.TimeoutInfo{
			Duration: 3 * time.Second, Height: height, Round: round, Step: 4,
		}}},
	}
	v.eqHex(t, "wal_timeout_proto", mustMarshal(t, walTimeout))
	walEnd := &cmtcons.TimedWALMessage{
		Time: fixedTime,
		Msg:  &cmtcons.WALMessage{Sum: &cmtcons.WALMessage_EndHeight{EndHeight: &cmtcons.EndHeight{Height: height}}},
	}
	v.eqHex(t, "wal_end_height_proto", mustMarshal(t, walEnd))
	walRS := &cmtcons.TimedWALMessage{
		Time: fixedTime,
		Msg: &cmtcons.WALMessage{Sum: &cmtcons.WALMessage_EventDataRoundState{EventDataRoundState: &cmtproto.EventDataRoundState{
			Height: height, Round: round, Step: "RoundStepPropose",
		}}},
	}
	v.eqHex(t, "wal_event_round_state_proto", mustMarshal(t, walRS))

	// MsgInfo.receive_time (field 3) is persisted exactly as on bera-v1.x, so
	// a proposal replayed from a WAL written by either line keeps its PBTS
	// timeliness verdict.
	rt := fixedTimeNext
	walProposalRT := &cmtcons.TimedWALMessage{
		Time: fixedTime,
		Msg: &cmtcons.WALMessage{Sum: &cmtcons.WALMessage_MsgInfo{MsgInfo: &cmtcons.MsgInfo{
			Msg: *msgs["p2p_proposal"], PeerID: "peer1", ReceiveTime: &rt,
		}}},
	}
	v.eqHex(t, "wal_msginfo_proposal_with_receive_time_proto", mustMarshal(t, walProposalRT))
	withRT := new(cmtcons.TimedWALMessage)
	require.NoError(t, withRT.Unmarshal(v.hex(t, "wal_msginfo_proposal_with_receive_time_proto")))
	mi, ok := withRT.Msg.Sum.(*cmtcons.WALMessage_MsgInfo)
	require.True(t, ok)
	assert.Equal(t, "peer1", mi.MsgInfo.PeerID)
	require.NotNil(t, mi.MsgInfo.ReceiveTime)
	assert.True(t, fixedTimeNext.Equal(*mi.MsgInfo.ReceiveTime))
	assert.True(t, fixedTime.Equal(withRT.Time))
	v.eqHex(t, "p2p_proposal", mustMarshal(t, &mi.MsgInfo.Msg))
}

func TestVectorsGenesisAndPrivval(t *testing.T) {
	v := loadVectors(t)
	f := newFixture(t)

	// genesis.json written by bera-v1.x
	genDoc, err := types.GenesisDocFromJSON([]byte(v.str(t, "genesis_json")))
	require.NoError(t, err)
	require.NoError(t, genDoc.ValidateAndComplete())
	assert.Equal(t, chainID, genDoc.ChainID)
	assert.True(t, fixedTime.Equal(genDoc.GenesisTime))
	assert.EqualValues(t, 1, genDoc.InitialHeight)
	assert.Equal(t, h32("genesis-app"), []byte(genDoc.AppHash))
	assert.JSONEq(t, `{"k":"v"}`, string(genDoc.AppState))
	require.NotNil(t, genDoc.ConsensusParams)
	assert.Equal(t, f.params, *genDoc.ConsensusParams)
	v.eqHex(t, "params_hash", genDoc.ConsensusParams.Hash())
	v.eqHex(t, "genesis_validator_hash", genDoc.ValidatorHash())
	v.eqHex(t, "bls_valset_hash", genDoc.ValidatorHash())
	require.Len(t, genDoc.Validators, numVals)
	for i, gv := range genDoc.Validators {
		assert.True(t, f.blsVals[i].PubKey.Equals(gv.PubKey), "genesis validator %d pubkey", i)
		assert.Equal(t, f.blsVals[i].Address, gv.Address)
		assert.Equal(t, f.blsVals[i].VotingPower, gv.Power)
	}
	// and it re-serializes to the same document apart from the extra
	// "authority" consensus param object this fork carries
	tmp := t.TempDir()
	require.NoError(t, genDoc.SaveAs(filepath.Join(tmp, "genesis.json")))
	reread, err := os.ReadFile(filepath.Join(tmp, "genesis.json"))
	require.NoError(t, err)
	var got, want map[string]json.RawMessage
	require.NoError(t, json.Unmarshal(reread, &got))
	require.NoError(t, json.Unmarshal([]byte(v.str(t, "genesis_json")), &want))
	for k := range want {
		if k == "consensus_params" {
			continue // checked above (modulo "authority")
		}
		assert.JSONEqf(t, string(want[k]), string(got[k]), "genesis.%s differs", k)
	}

	// priv_validator_key.json / priv_validator_state.json written by bera-v1.x
	keyFile := filepath.Join(tmp, "priv_validator_key.json")
	stateFile := filepath.Join(tmp, "priv_validator_state.json")
	require.NoError(t, os.WriteFile(keyFile, []byte(v.str(t, "priv_validator_key_json")), 0o600))
	require.NoError(t, os.WriteFile(stateFile, []byte(v.str(t, "priv_validator_state_json")), 0o600))
	pv := privval.LoadFilePV(keyFile, stateFile)
	pub, err := pv.GetPubKey()
	require.NoError(t, err)
	v.eqHex(t, "privval_pubkey", pub.Bytes())
	assert.True(t, f.blsVals[0].PubKey.Equals(pub))
	pvProp := types.NewProposal(height, round, -1, f.blockID, fixedTime).ToProto()
	require.NoError(t, pv.SignProposal(chainID, pvProp))
	v.eqHex(t, "privval_signed_proposal_signature", pvProp.Signature)
	pvVote := f.vote(cmtproto.PrecommitType, f.blockID, 0, f.blsVals[0].Address).ToProto()
	require.NoError(t, pv.SignVote(chainID, pvVote))
	v.eqHex(t, "privval_signed_vote_signature", pvVote.Signature)
	// FilePV on this fork always signs the (empty) vote extension of a non-nil
	// precommit; bera-v1.x's FilePV was asked not to. Consensus strips the
	// extension signature when vote extensions are disabled (see
	// types.SignAndCheckVote), so the vote that reaches the wire is identical.
	require.NotEmpty(t, pvVote.ExtensionSignature)
	pvVote.ExtensionSignature = nil
	v.eqHex(t, "privval_signed_vote_proto", mustMarshal(t, pvVote))
	// the last-signed state file matches bera-v1.x's (same height/round/step,
	// signature and sign bytes)
	stateAfter, err := os.ReadFile(stateFile)
	require.NoError(t, err)
	assert.JSONEq(t, v.str(t, "priv_validator_state_json_after_signing"), string(stateAfter))
	// a key file written by this fork is byte-identical to the bera-v1.x one
	pv2 := privval.NewFilePV(f.blsPrivs[0], filepath.Join(tmp, "k2.json"), filepath.Join(tmp, "s2.json"))
	pv2.Save()
	k2, err := os.ReadFile(filepath.Join(tmp, "k2.json"))
	require.NoError(t, err)
	assert.JSONEq(t, v.str(t, "priv_validator_key_json"), string(k2))
	s2, err := os.ReadFile(filepath.Join(tmp, "s2.json"))
	require.NoError(t, err)
	assert.JSONEq(t, v.str(t, "priv_validator_state_json"), string(s2))
	bz, err := cmtjson.Marshal(f.blsPrivs[0])
	require.NoError(t, err)
	assert.JSONEq(t, v.str(t, "bls_privkey0_cmtjson"), string(bz))
	v.eqHex(t, "bls_privkey0_bytes", f.blsPrivs[0].Bytes())
	pvEd := privval.NewFilePV(f.edPriv, filepath.Join(tmp, "ed.json"), filepath.Join(tmp, "ed_state.json"))
	pvEd.Save()
	ed, err := os.ReadFile(filepath.Join(tmp, "ed.json"))
	require.NoError(t, err)
	assert.JSONEq(t, v.str(t, "priv_validator_key_ed25519_json"), string(ed))
}

// TestWriteV040Outputs writes this fork's values for the shared inputs (same
// schema as vectors/bera_v1x_vectors.json, plus a few fork-specific extras) to
// the path in BERA_COMPAT_WRITE_OUTPUTS, for the reverse check performed by
// "gen-v1x -verify" (bera-v1.x decoding what this fork produces). It is a
// no-op unless the variable is set. See README.md.
func TestWriteV040Outputs(t *testing.T) {
	path := os.Getenv("BERA_COMPAT_WRITE_OUTPUTS")
	if path == "" {
		t.Skip("BERA_COMPAT_WRITE_OUTPUTS not set")
	}
	f := newFixture(t)
	out := map[string]any{}
	hx := hex.EncodeToString

	agg := f.aggCommit(t)
	out["agg_commit_proto"] = hx(mustMarshal(t, agg.ToProto()))
	out["agg_commit_hash"] = hx(agg.Hash())
	block, ps := f.block(t, agg)
	bp, err := block.ToProto()
	require.NoError(t, err)
	out["block_proto"] = hx(mustMarshal(t, bp))
	out["block_hash"] = hx(block.Hash())
	out["header_hash"] = hx(block.Header.Hash())
	out["block_partset_hash"] = hx(ps.Hash())
	out["block_meta_proto"] = hx(mustMarshal(t, types.NewBlockMeta(block, ps).ToProto()))
	precommit := f.signedBLSVote(t, f.blockID, 0)
	out["vote_proto_signed_precommit"] = hx(mustMarshal(t, precommit.ToProto()))
	out["vote_sign_bytes_precommit"] = hx(types.VoteSignBytes(chainID, precommit.ToProto()))
	proposal := types.NewProposal(height, round, 1, f.blockID, fixedTime)
	psig, err := f.blsPrivs[1].Sign(types.ProposalSignBytes(chainID, proposal.ToProto()))
	require.NoError(t, err)
	proposal.Signature = psig
	out["proposal_proto_signed"] = hx(mustMarshal(t, proposal.ToProto()))
	out["proposal_sign_bytes"] = hx(types.ProposalSignBytes(chainID, proposal.ToProto()))
	pp := f.params.ToProto()
	out["params_proto"] = hx(mustMarshal(t, &pp))
	out["params_hash"] = hx(f.params.Hash())
	bz, err := cmtjson.Marshal(f.params)
	require.NoError(t, err)
	out["params_json"] = string(bz)
	vsp, err := f.blsValSet.ToProto()
	require.NoError(t, err)
	out["bls_valset_proto"] = hx(mustMarshal(t, vsp))
	out["bls_valset_hash"] = hx(f.blsValSet.Hash())
	state := sm.State{
		Version:                          cmtstate.Version{Consensus: cmtversion.Consensus{Block: 11, App: 1}, Software: "1.0.1"},
		ChainID:                          chainID,
		InitialHeight:                    1,
		LastBlockHeight:                  height,
		LastBlockID:                      f.blockID,
		LastBlockTime:                    fixedTime,
		NextValidators:                   f.blsValSet.Copy(),
		Validators:                       f.blsValSet.Copy(),
		LastValidators:                   f.blsValSet.Copy(),
		LastHeightValidatorsChanged:      100,
		ConsensusParams:                  f.params,
		LastHeightConsensusParamsChanged: 50,
		LastResultsHash:                  h32("results"),
		AppHash:                          h32("app"),
		NextBlockDelay:                   1500 * time.Millisecond,
	}
	sp, err := state.ToProto()
	require.NoError(t, err)
	out["state_proto"] = hx(mustMarshal(t, sp))
	for name, m := range f.p2pMessages(t) {
		out[name] = hx(mustMarshal(t, m))
	}
	walVote := &cmtcons.TimedWALMessage{
		Time: fixedTime,
		Msg:  &cmtcons.WALMessage{Sum: &cmtcons.WALMessage_MsgInfo{MsgInfo: &cmtcons.MsgInfo{Msg: *f.p2pMessages(t)["p2p_vote"], PeerID: ""}}},
	}
	out["wal_msginfo_vote_proto"] = hx(mustMarshal(t, walVote))
	rt := fixedTimeNext
	walProposalRT := &cmtcons.TimedWALMessage{
		Time: fixedTime,
		Msg: &cmtcons.WALMessage{Sum: &cmtcons.WALMessage_MsgInfo{MsgInfo: &cmtcons.MsgInfo{
			Msg: *f.p2pMessages(t)["p2p_proposal"], PeerID: "peer1", ReceiveTime: &rt,
		}}},
	}
	out["wal_msginfo_proposal_with_receive_time_proto"] = hx(mustMarshal(t, walProposalRT))
	voteA := f.signedBLSVote(t, f.blockID, 2)
	otherBlockID := types.BlockID{Hash: h32("other-block"), PartSetHeader: types.PartSetHeader{Total: 3, Hash: h32("other-parts")}}
	voteB := f.signedBLSVote(t, otherBlockID, 2)
	dve, err := types.NewDuplicateVoteEvidence(voteA, voteB, fixedTime, f.blsValSet)
	require.NoError(t, err)
	evp, err := types.EvidenceToProto(dve)
	require.NoError(t, err)
	out["dve_proto"] = hx(mustMarshal(t, evp))
	out["dve_hash"] = hx(dve.Hash())

	// Fork-specific extras, for bera-v1.x to decode:
	// the FinalizeBlock response exactly as this fork persists it (pub_key set
	// by the app, pub_key_bytes/pub_key_type added on save) ...
	fbr := &abci.ResponseFinalizeBlock{
		ValidatorUpdates:      []abci.ValidatorUpdate{types.TM2PB.NewValidatorUpdate(f.blsVals[0].PubKey, 77)},
		ConsensusParamUpdates: paramsUpdate(),
		AppHash:               h32("app-next"),
		NextBlockDelay:        1500 * time.Millisecond,
	}
	fbr.ValidatorUpdates = types.NormalizeValidatorUpdates(fbr.ValidatorUpdates)
	out["v040_finalize_block_response_proto"] = hx(mustMarshal(t, fbr))
	out["v040_abci_responses_info_proto"] = hx(mustMarshal(t, &cmtstate.ABCIResponsesInfo{ResponseFinalizeBlock: fbr, Height: height}))
	// ... a genesis file written by this fork (carries the extra "authority" object) ...
	genDoc := types.GenesisDoc{
		GenesisTime:     fixedTime,
		ChainID:         chainID,
		InitialHeight:   1,
		ConsensusParams: &f.params,
		AppHash:         h32("genesis-app"),
		AppState:        json.RawMessage(`{"k":"v"}`),
	}
	for i := 0; i < numVals; i++ {
		genDoc.Validators = append(genDoc.Validators, types.GenesisValidator{
			Address: f.blsVals[i].Address, PubKey: f.blsVals[i].PubKey, Power: f.blsVals[i].VotingPower, Name: fmt.Sprintf("val%d", i),
		})
	}
	require.NoError(t, genDoc.ValidateAndComplete())
	tmp := t.TempDir()
	require.NoError(t, genDoc.SaveAs(filepath.Join(tmp, "genesis.json")))
	gj, err := os.ReadFile(filepath.Join(tmp, "genesis.json"))
	require.NoError(t, err)
	out["v040_genesis_json"] = string(gj)
	out["genesis_validator_hash"] = hx(genDoc.ValidatorHash())
	// ... and the key/state files written by this fork.
	pv := privval.NewFilePV(f.blsPrivs[0], filepath.Join(tmp, "k.json"), filepath.Join(tmp, "s.json"))
	pv.Save()
	kj, err := os.ReadFile(filepath.Join(tmp, "k.json"))
	require.NoError(t, err)
	out["v040_priv_validator_key_json"] = string(kj)
	sj, err := os.ReadFile(filepath.Join(tmp, "s.json"))
	require.NoError(t, err)
	out["v040_priv_validator_state_json"] = string(sj)

	out["_source"] = "generated by test/compat TestWriteV040Outputs against bera-v0.40.x"
	bz, err = json.MarshalIndent(out, "", "  ")
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(path, append(bz, '\n'), 0o644))
	t.Logf("wrote %s", path)
}

func TestVectorsBLSAggregation(t *testing.T) {
	v := loadVectors(t)
	f := newFixture(t)
	msg := []byte(v.str(t, "bls_aggregate_message"))
	sigs := make([][]byte, numVals)
	pubs := make([]*bls12381.PubKey, numVals)
	for i := 0; i < numVals; i++ {
		sig, err := f.blsPrivs[i].Sign(msg)
		require.NoError(t, err)
		sigs[i] = sig
		pubs[i] = blsPubPtr(f.blsPrivs[i].PubKey())
	}
	agg, err := bls12381.AggregateSignatures(sigs)
	require.NoError(t, err)
	v.eqHex(t, "bls_aggregate_signature", agg)
	assert.True(t, bls12381.VerifyAggregateSignature(agg, pubs, msg))
	assert.True(t, bls12381.VerifyAggregateSignature(v.hex(t, "bls_aggregate_signature"), pubs, msg))
}
