name: e2e
# Runs the CI end-to-end test network on all pushes to main or release branches
# and every pull request, but only if any Go files have been changed.
on:
  workflow_dispatch:  # allow running workflow manually
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - v0.3[478].x
      - v[1-9][0-9]?.x

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  e2e-test:
    # Run parallel jobs for `ci.toml`, `libp2p-ci.toml`, and regression manifests
    strategy:
      fail-fast: false
      matrix:
        group: ['networks/ci', 'networks/libp2p-ci', 'networks_regressions/*']
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - id: filter
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        with:
          filters: |
            code:
              - '**/*.go'
              - 'Makefile'
              - 'go.*'

      - run: echo "GO_VERSION=$(cat .github/workflows/go-version.env | grep GO_VERSION | cut -d '=' -f2)" >> $GITHUB_ENV
        if: steps.filter.outputs.code == 'true'

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        if: steps.filter.outputs.code == 'true'
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        if: steps.filter.outputs.code == 'true'
        working-directory: test/e2e
        run: make -j2 docker runner

      - name: Run "${{ matrix.group }}"" testnet
        if: steps.filter.outputs.code == 'true'
        working-directory: test/e2e
        run: ./run-multiple.sh ${{ matrix.group }}.toml
